//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.Properties.languages1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp5.Properties.languages1.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtstag.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl löschen.
        /// </summary>
        public static string Clear_Selection {
            get {
                return ResourceManager.GetString("Clear Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenname.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelklicken Sie auf ein Element, um Details anzuzeigen.
        /// </summary>
        public static string Double_click_on_an_item_to_view_details {
            get {
                return ResourceManager.GetString("Double click on an item to view details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Veranstaltung.
        /// </summary>
        public static string Event_Date {
            get {
                return ResourceManager.GetString("Event Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein. Anzahl der Erwachsenen.
        /// </summary>
        public static string Expected_no__of_Adults {
            get {
                return ResourceManager.GetString("Expected no. of Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein. der Kinder.
        /// </summary>
        public static string Expected_no__of_Kids {
            get {
                return ResourceManager.GetString("Expected no. of Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelegenheit.
        /// </summary>
        public static string Occasion {
            get {
                return ResourceManager.GetString("Occasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retten.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochzeit.
        /// </summary>
        public static string Wedding {
            get {
                return ResourceManager.GetString("Wedding", resourceCulture);
            }
        }
    }
}
